services:
  postgres:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_jpa
    ports:
      - "5432:5432"